### ISSUE TITLE
General issues

### ISSUE THREAD

**Issue by rodriguez-facundo** [ariel-brassesco/testing#1]
The following line of code replaces the challenge of reading the value of `TRAVIS_PULL_REQUEST_BRANCH` with the challenge of reading the number of arguments passed to the copy.py script. The two things don't map one to one, so this would end up in the creation of bugs downstream.

https://github.com/ariel-brassesco/testing/blob/cc43116ebe990bcb0f5aba385ac19d572da9a036/copy.py#L63

There are two approaches to solve this issue:

- Env variables

```python
import os
TRAVIS_PULL_REQUEST_BRANCH = os.environ.get('TRAVIS_PULL_REQUEST_BRANCH', '')
if TRAVIS_PULL_REQUEST_BRANCH == '':
     test = 'PUSH'
```

- argparse

```python
parser = argparse.ArgumentParser(
        description='This script clones and checkout branches bla bla bla...')

    parser.add_argument('-b', '--travis-branch', dest='travis_branch', default...
                        help='Specify the travis branch bla bla')

    parser.add_argument('-p', '--travis-pr-branch', dest='travis_pr_branch', default...
                        help='Specify the travis branch bla bla')
```

---

Given that this python code is meant to be run as a bash script, we need to use argparse module to give the user more information about the script:

```sh
copy.py -h
```

But at the same time, the script will be use from inside a docker container with the env variables already set up. So it is useful to have the first approach also. So I would suggest to use a combination of both. Were we accept something like this

```bash
copy.py --travis-branch 'feature/33' --travis-pr_branch 'development' -default-branch 'master'
```

But at the same time, if we don't provide those values, then the script will attempt to find them like this

```python
travis_pr_branch = os.environ.get('TRAVIS_PULL_REQUEST_BRANCH', '')
```

The script should inform the user of what is going on:

```
No args provides
Found env variable TRAVIS_PULL_REQUEST_BRANCH with value 'feature/44'
or
arg travis-branch "feature/44"
or
no arg-value 
no env variable
exiting execution
```

---

We don't know if the user is entering the args in the right order. The solution to avoid future bugs it to implement what was described above.

https://github.com/ariel-brassesco/testing/blob/cc43116ebe990bcb0f5aba385ac19d572da9a036/copy.py#L72

--- 

By convention, the word test is reserved for testing code. This function is to validate args.

https://github.com/ariel-brassesco/testing/blob/cc43116ebe990bcb0f5aba385ac19d572da9a036/copy.py#L51

--- 

main is usually reserved for a few lines of code. The content of main is doing many things. It would be better if the logic is extracted to a function.

https://github.com/ariel-brassesco/testing/blob/cc43116ebe990bcb0f5aba385ac19d572da9a036/copy.py#L86

---

```python
try:
    pass
except:
    pass
```

Are usually reserved for things that are outside our control. I don't know if this python git client has some way of asserting the existence of a branch

```python
repo.has_branch('something')
```

If it does, it would be better to replace the try except with that method. If it doesn't, then we go with `try` and `except`.

---

Let's create a print method so that we carve the code

https://github.com/ariel-brassesco/testing/blob/cc43116ebe990bcb0f5aba385ac19d572da9a036/copy.py#L113

```python
cprint(f"Start cloning {clone_url}.", color=Fore.YELLOW)
```

---

The rest looks good 👍

**Comment by ariel-brassesco** [comment]
Finally implement argparse and check with Travis env variables defined.
There is not a function like has_branch('name_branch'), so I think the best is to handle the exception.
I figure out that repo.git.checkout('') make a checkout in the current branch and return a True value, so i fix it.

**Comment by rodriguez-facundo** [comment]
eval should be replaced by getattr(Fore, color, 'WHITE')

https://github.com/ariel-brassesco/testing/blob/972ba97cb392eb33e9bb03e63bab28d043f6d48f/copy.py#L152

- What happens if the value of color is `khsbkhdbf`, 22, [1,23], {}, or any other thing?

---

```bash
Traceback (most recent call last):
  File "copy.py", line 1, in <module>
    from git import Repo
ModuleNotFoundError: No module named 'git'
```

```bash
Traceback (most recent call last):
  File "copy.py", line 3, in <module>
    from colorama import Fore
ModuleNotFoundError: No module named 'colorama'
```

Let's create a requirement.txt file and a README.md where we tell people these modules are part of the requirements

---

- Let's use google docs or grammarly to check grammar. 
- `If PR or PUSH`: lets say something along these lines: `if the current travis test corresponds to a PR test, then.... `

---

This line is executed twice. Should be replaced by `args.target = os.environ.get('TRAVIS_BRANCH')` and then just check whether or not args.target was assigned a value

https://github.com/ariel-brassesco/testing/blob/972ba97cb392eb33e9bb03e63bab28d043f6d48f/copy.py#L129

Same here

https://github.com/ariel-brassesco/testing/blob/972ba97cb392eb33e9bb03e63bab28d043f6d48f/copy.py#L137

---

This is assigning a value that was already assigned above

https://github.com/ariel-brassesco/testing/blob/972ba97cb392eb33e9bb03e63bab28d043f6d48f/copy.py#L139

---

Values like 'development', 'PR' and any other constant string need to be defined at the top of the script and use a map to get them. Otherwise, when you need to change something you would have to navigate the code finding where this string were defined

```python
constants = {
    "default_branch": "development",
    "pr": 'PR'
}

default_branch = constants['pr']
```

---

Lets refactor the general information  a little like this

```
INFO
#############
Repository url: ...
Travis test mode: ...
------------------
Origin branch: ...
Target branch: ...
Default branch: ...
------------------
```

https://github.com/ariel-brassesco/testing/blob/972ba97cb392eb33e9bb03e63bab28d043f6d48f/copy.py#L170

---

`checkout` and `merge` methods are still using bare print

**Comment by ariel-brassesco** [comment]
I added the requirement.txt. Replace the bare print in functions. Improved the cprint functions to work with any argument. Define some constants values and improved the information.

**Comment by rodriguez-facundo** [comment]
We are still using try/except to check whether a branch exists or not. We have to replace that with something else.

**Comment by rodriguez-facundo** [comment]
> There is not a function like has_branch('name_branch'), so I think the best is to handle the exception.

```python
from git import Git
g = Git()
g.branch('-r')
```

**Comment by rodriguez-facundo** [comment]
We also need to be able to checkout tags and fail safely to checkout tags.
Try adding a couple tags to this repo and use them as TRAVIS env variables
